package com.reservaciones.mapeos;
// Generated 30/07/2013 03:44:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private Date fechacreacion;
     private Set rolesPermisoses = new HashSet(0);
     private Set permisosAccioneses = new HashSet(0);

    public Permisos() {
    }

	
    public Permisos(int id) {
        this.id = id;
    }
    public Permisos(int id, String nombre, String descripcion, Date fechacreacion, Set rolesPermisoses, Set permisosAccioneses) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechacreacion = fechacreacion;
       this.rolesPermisoses = rolesPermisoses;
       this.permisosAccioneses = permisosAccioneses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }
    public Set getRolesPermisoses() {
        return this.rolesPermisoses;
    }
    
    public void setRolesPermisoses(Set rolesPermisoses) {
        this.rolesPermisoses = rolesPermisoses;
    }
    public Set getPermisosAccioneses() {
        return this.permisosAccioneses;
    }
    
    public void setPermisosAccioneses(Set permisosAccioneses) {
        this.permisosAccioneses = permisosAccioneses;
    }




}


