package com.reservaciones.mapeos;
// Generated 30/07/2013 03:44:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PermisosAcciones generated by hbm2java
 */
public class PermisosAcciones  implements java.io.Serializable {


     private int id;
     private PermisoAcciones permisoAcciones;
     private Permisos permisos;
     private Date fechacreacion;

    public PermisosAcciones() {
    }

	
    public PermisosAcciones(int id) {
        this.id = id;
    }
    public PermisosAcciones(int id, PermisoAcciones permisoAcciones, Permisos permisos, Date fechacreacion) {
       this.id = id;
       this.permisoAcciones = permisoAcciones;
       this.permisos = permisos;
       this.fechacreacion = fechacreacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public PermisoAcciones getPermisoAcciones() {
        return this.permisoAcciones;
    }
    
    public void setPermisoAcciones(PermisoAcciones permisoAcciones) {
        this.permisoAcciones = permisoAcciones;
    }
    public Permisos getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Permisos permisos) {
        this.permisos = permisos;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }




}


