package com.reservaciones.mapeos;
// Generated 30/07/2013 03:44:33 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int id;
     private String matricula;
     private String nombre;
     private String password;
     private String apellido1;
     private String apellido2;
     private String sexo;
     private Date fechanacimiento;
     private String pais;
     private String estado;
     private String puesto;
     private Boolean online;
     private String descripcion;
     private Date fechacreacion;
     private Set rolesUsuarioses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(int id) {
        this.id = id;
    }
    public Usuarios(int id, String matricula, String nombre, String password, String apellido1, String apellido2, String sexo, Date fechanacimiento, String pais, String estado, String puesto, Boolean online, String descripcion, Date fechacreacion, Set rolesUsuarioses) {
       this.id = id;
       this.matricula = matricula;
       this.nombre = nombre;
       this.password = password;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.sexo = sexo;
       this.fechanacimiento = fechanacimiento;
       this.pais = pais;
       this.estado = estado;
       this.puesto = puesto;
       this.online = online;
       this.descripcion = descripcion;
       this.fechacreacion = fechacreacion;
       this.rolesUsuarioses = rolesUsuarioses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public Boolean getOnline() {
        return this.online;
    }
    
    public void setOnline(Boolean online) {
        this.online = online;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }
    public Set getRolesUsuarioses() {
        return this.rolesUsuarioses;
    }
    
    public void setRolesUsuarioses(Set rolesUsuarioses) {
        this.rolesUsuarioses = rolesUsuarioses;
    }




}


