package com.reservaciones.mapeos.reserv;
// Generated 22/08/2013 12:51:15 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set objetoReservables = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int id) {
        this.id = id;
    }
    public Categoria(int id, String descripcion, Set objetoReservables) {
       this.id = id;
       this.descripcion = descripcion;
       this.objetoReservables = objetoReservables;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getObjetoReservables() {
        return this.objetoReservables;
    }
    
    public void setObjetoReservables(Set objetoReservables) {
        this.objetoReservables = objetoReservables;
    }




}


