package com.reservaciones.mapeos.reserv;
// Generated 22/08/2013 12:51:15 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Consumo generated by hbm2java
 */
public class Consumo  implements java.io.Serializable {


     private int id;
     private ObjetoReservable objetoReservable;
     private Servicios servicios;
     private Date fechaconsumo;
     private Double totalconsumo;

    public Consumo() {
    }

	
    public Consumo(int id) {
        this.id = id;
    }
    public Consumo(int id, ObjetoReservable objetoReservable, Servicios servicios, Date fechaconsumo, Double totalconsumo) {
       this.id = id;
       this.objetoReservable = objetoReservable;
       this.servicios = servicios;
       this.fechaconsumo = fechaconsumo;
       this.totalconsumo = totalconsumo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ObjetoReservable getObjetoReservable() {
        return this.objetoReservable;
    }
    
    public void setObjetoReservable(ObjetoReservable objetoReservable) {
        this.objetoReservable = objetoReservable;
    }
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
    public Date getFechaconsumo() {
        return this.fechaconsumo;
    }
    
    public void setFechaconsumo(Date fechaconsumo) {
        this.fechaconsumo = fechaconsumo;
    }
    public Double getTotalconsumo() {
        return this.totalconsumo;
    }
    
    public void setTotalconsumo(Double totalconsumo) {
        this.totalconsumo = totalconsumo;
    }




}


