package com.reservaciones.mapeos.reserv;
// Generated 22/08/2013 12:51:15 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * EstadoObjetoReservable generated by hbm2java
 */
public class EstadoObjetoReservable  implements java.io.Serializable {


     private long id;
     private Motivo motivo;
     private ObjetoReservable objetoReservable;
     private Date fechadesde;
     private Date fechahasta;

    public EstadoObjetoReservable() {
    }

	
    public EstadoObjetoReservable(long id) {
        this.id = id;
    }
    public EstadoObjetoReservable(long id, Motivo motivo, ObjetoReservable objetoReservable, Date fechadesde, Date fechahasta) {
       this.id = id;
       this.motivo = motivo;
       this.objetoReservable = objetoReservable;
       this.fechadesde = fechadesde;
       this.fechahasta = fechahasta;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Motivo getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(Motivo motivo) {
        this.motivo = motivo;
    }
    public ObjetoReservable getObjetoReservable() {
        return this.objetoReservable;
    }
    
    public void setObjetoReservable(ObjetoReservable objetoReservable) {
        this.objetoReservable = objetoReservable;
    }
    public Date getFechadesde() {
        return this.fechadesde;
    }
    
    public void setFechadesde(Date fechadesde) {
        this.fechadesde = fechadesde;
    }
    public Date getFechahasta() {
        return this.fechahasta;
    }
    
    public void setFechahasta(Date fechahasta) {
        this.fechahasta = fechahasta;
    }




}


