package com.reservaciones.mapeos.reserv;
// Generated 22/08/2013 12:51:15 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Historico generated by hbm2java
 */
public class Historico  implements java.io.Serializable {


     private int id;
     private ObjetoReservable objetoReservable;
     private Motivo motivo;
     private Date desde;
     private Date hasta;

    public Historico() {
    }

	
    public Historico(int id) {
        this.id = id;
    }
    public Historico(int id, ObjetoReservable objetoReservable, Motivo motivo, Date desde, Date hasta) {
       this.id = id;
       this.objetoReservable = objetoReservable;
       this.motivo = motivo;
       this.desde = desde;
       this.hasta = hasta;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ObjetoReservable getObjetoReservable() {
        return this.objetoReservable;
    }
    
    public void setObjetoReservable(ObjetoReservable objetoReservable) {
        this.objetoReservable = objetoReservable;
    }
    public Motivo getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(Motivo motivo) {
        this.motivo = motivo;
    }
    public Date getDesde() {
        return this.desde;
    }
    
    public void setDesde(Date desde) {
        this.desde = desde;
    }
    public Date getHasta() {
        return this.hasta;
    }
    
    public void setHasta(Date hasta) {
        this.hasta = hasta;
    }




}


