package com.reservaciones.mapeos.reserv;
// Generated 22/08/2013 12:51:15 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Motivo generated by hbm2java
 */
public class Motivo  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set historicos = new HashSet(0);
     private Set estadoObjetoReservables = new HashSet(0);

    public Motivo() {
    }

	
    public Motivo(int id) {
        this.id = id;
    }
    public Motivo(int id, String descripcion, Set historicos, Set estadoObjetoReservables) {
       this.id = id;
       this.descripcion = descripcion;
       this.historicos = historicos;
       this.estadoObjetoReservables = estadoObjetoReservables;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getHistoricos() {
        return this.historicos;
    }
    
    public void setHistoricos(Set historicos) {
        this.historicos = historicos;
    }
    public Set getEstadoObjetoReservables() {
        return this.estadoObjetoReservables;
    }
    
    public void setEstadoObjetoReservables(Set estadoObjetoReservables) {
        this.estadoObjetoReservables = estadoObjetoReservables;
    }




}


