package com.reservaciones.mapeos.reserv;
// Generated 22/08/2013 12:51:15 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ObjetoReservable generated by hbm2java
 */
public class ObjetoReservable  implements java.io.Serializable {


     private int id;
     private Categoria categoria;
     private String nombre;
     private String descripcion;
     private Set estadoObjetoReservables = new HashSet(0);
     private Set consumos = new HashSet(0);
     private Set reservases = new HashSet(0);
     private Set historicos = new HashSet(0);

    public ObjetoReservable() {
    }

	
    public ObjetoReservable(int id) {
        this.id = id;
    }
    public ObjetoReservable(int id, Categoria categoria, String nombre, String descripcion, Set estadoObjetoReservables, Set consumos, Set reservases, Set historicos) {
       this.id = id;
       this.categoria = categoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estadoObjetoReservables = estadoObjetoReservables;
       this.consumos = consumos;
       this.reservases = reservases;
       this.historicos = historicos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEstadoObjetoReservables() {
        return this.estadoObjetoReservables;
    }
    
    public void setEstadoObjetoReservables(Set estadoObjetoReservables) {
        this.estadoObjetoReservables = estadoObjetoReservables;
    }
    public Set getConsumos() {
        return this.consumos;
    }
    
    public void setConsumos(Set consumos) {
        this.consumos = consumos;
    }
    public Set getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set reservases) {
        this.reservases = reservases;
    }
    public Set getHistoricos() {
        return this.historicos;
    }
    
    public void setHistoricos(Set historicos) {
        this.historicos = historicos;
    }




}


