package com.reservaciones.mapeos.reserv;
// Generated 22/08/2013 12:51:15 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Reservas generated by hbm2java
 */
public class Reservas  implements java.io.Serializable {


     private int id;
     private ObjetoReservable objetoReservable;
     private Long usuarioid;
     private Date fechadesde;
     private Date fechahasta;

    public Reservas() {
    }

	
    public Reservas(int id) {
        this.id = id;
    }
    public Reservas(int id, ObjetoReservable objetoReservable, Long usuarioid, Date fechadesde, Date fechahasta) {
       this.id = id;
       this.objetoReservable = objetoReservable;
       this.usuarioid = usuarioid;
       this.fechadesde = fechadesde;
       this.fechahasta = fechahasta;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ObjetoReservable getObjetoReservable() {
        return this.objetoReservable;
    }
    
    public void setObjetoReservable(ObjetoReservable objetoReservable) {
        this.objetoReservable = objetoReservable;
    }
    public Long getUsuarioid() {
        return this.usuarioid;
    }
    
    public void setUsuarioid(Long usuarioid) {
        this.usuarioid = usuarioid;
    }
    public Date getFechadesde() {
        return this.fechadesde;
    }
    
    public void setFechadesde(Date fechadesde) {
        this.fechadesde = fechadesde;
    }
    public Date getFechahasta() {
        return this.fechahasta;
    }
    
    public void setFechahasta(Date fechahasta) {
        this.fechahasta = fechahasta;
    }




}


