package com.reservaciones.mapeos.reserv;
// Generated 22/08/2013 12:51:15 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Servicios generated by hbm2java
 */
public class Servicios  implements java.io.Serializable {


     private long id;
     private String descripcion;
     private String cuotaPor;
     private Double monto;
     private Set consumos = new HashSet(0);

    public Servicios() {
    }

	
    public Servicios(long id) {
        this.id = id;
    }
    public Servicios(long id, String descripcion, String cuotaPor, Double monto, Set consumos) {
       this.id = id;
       this.descripcion = descripcion;
       this.cuotaPor = cuotaPor;
       this.monto = monto;
       this.consumos = consumos;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCuotaPor() {
        return this.cuotaPor;
    }
    
    public void setCuotaPor(String cuotaPor) {
        this.cuotaPor = cuotaPor;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Set getConsumos() {
        return this.consumos;
    }
    
    public void setConsumos(Set consumos) {
        this.consumos = consumos;
    }




}


